CC = g++
SRC = main.cpp
SIZES = 1000 10000 100000

FLAGS = \
   	-DMERGE_SORT \
    -DQUICK_SORT \
    -DRANDOMIZED_QUICK_SORT \
    -DHEAP_SORT \
    -DBUBBLE_SORT \
    -DSELECTION_SORT

# Targets for each algorithm
MERGE_SORT_BIN = sort_merge
QUICK_SORT_BIN = sort_quick
RANDQSORT_BIN = sort_randq
HEAP_SORT_BIN = sort_heap
BUBBLE_SORT_BIN = sort_bubble
SEL_SORT_BIN = sort_select